### ISSUE TITLE
Jump to file configuration on Mac OS

### ISSUE THREAD

**Issue by ksinas** [barbushin/php-console#81]
Firs of all it's really a cool tool for developers. But I run into one issue.

I didn't really get how does the Jump to file configuration on Mac OS works.
1. Debug::$editor = 'txmt://open/?url=file://%file&line=%line';
says that Debug class does not exist
2. if I call 		PhpConsole\Dispatcher\Debug::$editor 
it says that $editor is not declared in this class.

Am I missing here something or is this feature still not implemented?

**Comment by barbushin** [comment]
`This article is 99% based on Jan Dolecek's http://pla.nette.org/en/how-open-files-in-ide-from-debugger translation of Štěpán Svoboda's post Thank you, Jan and Štěpán!`

I did not tested how it works on OS X, because I don't have MacBook. You can try to google *override protocol handler in OS X*, may be you'll be more lucky to find information how to configure OS X so it will open your editor when URL like `editor://open/?file=%file&line=%line` is opened in browser.
