### ISSUE TITLE
Will not work over https

### ISSUE THREAD

**Issue by haleeben** [barbushin/php-console#98]
Hi

It works fine when using the http protocol but it doesn't work over https

Is there any way to get this to work over https?

Thanks

**Comment by barbushin** [comment]
Hi. 

Actually php-console already works overy SSL, see https://publer.ru/test/examples/features/debug_vars.php

Could you please provide URL of your web-site that having problems with php-console and ssl? I can try to find out what is wrong with it. Also I need to know version of PHP and Web-server you're using.

**Comment by haleeben** [comment]
Hi

Sorry for the delayed reply.

The url is bondicigars.com

PHPversion : 5.6
Server: Litespeed 5.0.3

Thanks

**Comment by barbushin** [comment]
When I open https://bondicigars.com I see that `PHP-Console-Postpone` header is coming lowercase as `php-console-postpone` http://i.imgur.com/gikCCcc.png I think it's because of LiteSpeed server, but it's okay.

So I just published PHP Conosole extension v3.0.37 that will handle headers in any case. You will get update in your browser in a few hours.

Thanks for report!

**Comment by haleeben** [comment]
Yep, I can confirm that the update fixed this issue. 

Thanks for this awesome tool :)
